[package]
name = "arpg-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
arpg-core.workspace = true
arpg-data.workspace = true
arpg-rules.workspace = true
arpg-sim.workspace = true
arpg-replay.workspace = true
arpg-ai.workspace = true
arpg-metrics.workspace = true
