[package]
name = "arpg-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
arpg-core.workspace = true
arpg-sim.workspace = true
arpg-metrics.workspace = true
arpg-protocol.workspace = true
arpg-persistence.workspace = true
prost.workspace = true
quinn.workspace = true
rcgen = "0.13"
rustls-pki-types = "1"
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
arpg-data.workspace = true
arpg-rules.workspace = true
rcgen = "0.13"
quinn.workspace = true
rustls-pki-types = "1"
prost.workspace = true
arpg-sim.workspace = true
arpg-metrics.workspace = true
